// Hand-written: NOT generated by Stainless. Safe to edit.

package cmd

import (
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/stretchr/testify/assert"
)

func TestMaskKey(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"empty", "", "(not set)"},
		{"short (4)", "abcd", "****"},
		{"short (8)", "abcdefgh", "****"},
		{"long (32)", "ABCDefghIJKLmnopQRSTuvwxYZABCDEF", "ABCD****CDEF"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, maskKey(tc.input))
		})
	}
}

func TestConfigSetModel_abortOnCtrlC(t *testing.T) {
	m := newConfigSetModel()
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyCtrlC})
	final := result.(configSetModel)
	assert.True(t, final.aborted)
}

func TestConfigSetModel_emptyAccessKeyRejected(t *testing.T) {
	m := newConfigSetModel()
	// Press Enter without typing anything
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	final := result.(configSetModel)
	assert.False(t, final.done)
	assert.False(t, final.aborted)
	assert.Contains(t, final.errMsg, "access key cannot be empty")
}

func TestConfigSetModel_emptySecretKeyRejected(t *testing.T) {
	m := newConfigSetModel()
	// Type a value for access key
	for _, r := range "myaccesskey" {
		var updated tea.Model
		updated, _ = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{r}})
		m = updated.(configSetModel)
	}
	// Move to secret key field
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	mid := result.(configSetModel)
	assert.Equal(t, 1, mid.current)
	assert.Empty(t, mid.errMsg)

	// Press Enter without typing secret key
	result2, _ := mid.Update(tea.KeyMsg{Type: tea.KeyEnter})
	final := result2.(configSetModel)
	assert.False(t, final.done)
	assert.Contains(t, final.errMsg, "secret key cannot be empty")
}

func TestConfigSetModel_fullFlow(t *testing.T) {
	m := newConfigSetModel()
	// Type access key
	for _, r := range "access123" {
		updated, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{r}})
		m = updated.(configSetModel)
	}
	// Press Enter to move to secret field
	updated, _ := m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	m = updated.(configSetModel)
	assert.Equal(t, 1, m.current)

	// Type secret key
	for _, r := range "secret456" {
		var up tea.Model
		up, _ = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{r}})
		m = up.(configSetModel)
	}
	// Press Enter to complete
	var up tea.Model
	up, _ = m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	m = up.(configSetModel)

	assert.True(t, m.done)
	assert.False(t, m.aborted)
	assert.Equal(t, "access123", m.inputs[0].Value())
	assert.Equal(t, "secret456", m.inputs[1].Value())
}

func TestConfigSetModel_nonTTY(t *testing.T) {
	orig := isTerminalFn
	defer func() { isTerminalFn = orig }()
	isTerminalFn = func(uintptr) bool { return false }

	err := runConfigSet()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "interactive terminal")
}

func TestConfigSetModel_viewContainsPrompts(t *testing.T) {
	m := newConfigSetModel()
	view := m.View()
	assert.True(t, strings.Contains(view, "Access Key"))
}
