// Hand-written: NOT generated by Stainless. Safe to edit.

// Package config manages Upbit CLI credentials stored in $HOME/.upbit/config.
//
// Credential resolution priority:
//  1. Environment variables: UPBIT_ACCESS_KEY, UPBIT_SECRET_KEY
//  2. Config file: $HOME/.upbit/config (TOML, [default] section)
//  3. Empty — callers decide how to handle absence
//
// Config file format:
//
//	[default]
//	access_key = "..."
//	secret_key = "..."
//
// The file is created/updated exclusively via Save, which enforces 0600
// permissions and creates the parent directory (0700) if absent.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/BurntSushi/toml"
)

// Source indicates where a credential value was loaded from.
type Source int

const (
	SourceNone Source = iota
	SourceEnv
	SourceFile
)

func (s Source) String() string {
	switch s {
	case SourceEnv:
		return "env"
	case SourceFile:
		return "file"
	default:
		return "none"
	}
}

// Credentials holds the access/secret key pair along with their load sources.
type Credentials struct {
	AccessKey       string
	SecretKey       string
	AccessKeySource Source
	SecretKeySource Source
}

// IsEmpty reports whether both keys are absent.
func (c Credentials) IsEmpty() bool {
	return c.AccessKey == "" && c.SecretKey == ""
}

type configFile struct {
	Default struct {
		AccessKey string `toml:"access_key"`
		SecretKey string `toml:"secret_key"`
	} `toml:"default"`
}

// Path returns the absolute path to the config file ($HOME/.upbit/config).
func Path() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("could not determine home directory: %w", err)
	}
	return filepath.Join(home, ".upbit", "config"), nil
}

// Load reads credentials with priority: env > ~/.upbit/config > empty.
func Load() (Credentials, error) {
	return LoadFrom(os.UserHomeDir, os.Getenv)
}

// LoadFrom is the testable version of Load. homeDir and getenv are injectable.
func LoadFrom(homeDir func() (string, error), getenv func(string) string) (Credentials, error) {
	home, err := homeDir()
	if err != nil {
		return Credentials{}, fmt.Errorf("could not determine home directory: %w", err)
	}

	configPath := filepath.Join(home, ".upbit", "config")
	file, fileErr := readFile(configPath)
	if fileErr != nil {
		return Credentials{}, fileErr
	}

	var creds Credentials

	if v := getenv("UPBIT_ACCESS_KEY"); v != "" {
		creds.AccessKey = v
		creds.AccessKeySource = SourceEnv
	} else if file.Default.AccessKey != "" {
		creds.AccessKey = file.Default.AccessKey
		creds.AccessKeySource = SourceFile
	}

	if v := getenv("UPBIT_SECRET_KEY"); v != "" {
		creds.SecretKey = v
		creds.SecretKeySource = SourceEnv
	} else if file.Default.SecretKey != "" {
		creds.SecretKey = file.Default.SecretKey
		creds.SecretKeySource = SourceFile
	}

	return creds, nil
}

// LoadFile reads credentials from the config file only (no env lookup).
func LoadFile() (Credentials, error) {
	path, err := Path()
	if err != nil {
		return Credentials{}, err
	}
	file, err := readFile(path)
	if err != nil {
		return Credentials{}, err
	}
	var creds Credentials
	if file.Default.AccessKey != "" {
		creds.AccessKey = file.Default.AccessKey
		creds.AccessKeySource = SourceFile
	}
	if file.Default.SecretKey != "" {
		creds.SecretKey = file.Default.SecretKey
		creds.SecretKeySource = SourceFile
	}
	return creds, nil
}

// Save writes credentials to $HOME/.upbit/config with 0600 permissions.
func Save(c Credentials) error {
	path, err := Path()
	if err != nil {
		return err
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("could not create directory %s: %w", dir, err)
	}

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("could not write to %s: %w", path, err)
	}
	defer f.Close()

	// Fix permissions if the file pre-existed with loose permissions.
	if err := os.Chmod(path, 0600); err != nil {
		return fmt.Errorf("could not set permissions on %s: %w", path, err)
	}

	header := "# Upbit CLI credentials.\n# Managed by `upbit config set`. Do not edit manually unless you know what you are doing.\n\n"
	if _, err := f.WriteString(header); err != nil {
		return err
	}

	cfg := configFile{}
	cfg.Default.AccessKey = c.AccessKey
	cfg.Default.SecretKey = c.SecretKey

	return toml.NewEncoder(f).Encode(cfg)
}

// readFile parses the TOML config file. Returns empty configFile if file does not exist.
func readFile(path string) (configFile, error) {
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return configFile{}, nil
	}
	if err != nil {
		return configFile{}, fmt.Errorf("could not open %s: %w", path, err)
	}
	defer f.Close()

	if runtime.GOOS != "windows" {
		if info, statErr := f.Stat(); statErr == nil {
			if perm := info.Mode().Perm(); perm&0077 != 0 {
				fmt.Fprintf(os.Stderr, "warning: %s has loose permissions (found: 0%o, expected: 0600)\n", path, perm)
			}
		}
	}

	var cfg configFile
	if _, err := toml.NewDecoder(f).Decode(&cfg); err != nil {
		return configFile{}, fmt.Errorf("failed to parse %s: %w (try running 'upbit config set' to re-create it)", path, err)
	}
	return cfg, nil
}
