// Hand-written: NOT generated by Stainless. Safe to edit.

package config

import (
	"bytes"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/BurntSushi/toml"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLoadFrom_allEmpty(t *testing.T) {
	home := t.TempDir()
	creds, err := LoadFrom(func() (string, error) { return home, nil }, func(string) string { return "" })
	require.NoError(t, err)
	assert.Equal(t, SourceNone, creds.AccessKeySource)
	assert.Equal(t, SourceNone, creds.SecretKeySource)
	assert.Empty(t, creds.AccessKey)
	assert.Empty(t, creds.SecretKey)
}

func TestLoadFrom_envOnly(t *testing.T) {
	home := t.TempDir()
	env := map[string]string{
		"UPBIT_ACCESS_KEY": "access-from-env",
		"UPBIT_SECRET_KEY": "secret-from-env",
	}
	creds, err := LoadFrom(func() (string, error) { return home, nil }, func(k string) string { return env[k] })
	require.NoError(t, err)
	assert.Equal(t, "access-from-env", creds.AccessKey)
	assert.Equal(t, SourceEnv, creds.AccessKeySource)
	assert.Equal(t, "secret-from-env", creds.SecretKey)
	assert.Equal(t, SourceEnv, creds.SecretKeySource)
}

func TestLoadFrom_fileOnly(t *testing.T) {
	home := t.TempDir()
	writeTestConfig(t, home, "file-access", "file-secret")

	creds, err := LoadFrom(func() (string, error) { return home, nil }, func(string) string { return "" })
	require.NoError(t, err)
	assert.Equal(t, "file-access", creds.AccessKey)
	assert.Equal(t, SourceFile, creds.AccessKeySource)
	assert.Equal(t, "file-secret", creds.SecretKey)
	assert.Equal(t, SourceFile, creds.SecretKeySource)
}

func TestLoadFrom_envOverridesFile(t *testing.T) {
	home := t.TempDir()
	writeTestConfig(t, home, "file-access", "file-secret")

	env := map[string]string{
		"UPBIT_ACCESS_KEY": "env-access",
		"UPBIT_SECRET_KEY": "env-secret",
	}
	creds, err := LoadFrom(func() (string, error) { return home, nil }, func(k string) string { return env[k] })
	require.NoError(t, err)
	assert.Equal(t, "env-access", creds.AccessKey)
	assert.Equal(t, SourceEnv, creds.AccessKeySource)
	assert.Equal(t, "env-secret", creds.SecretKey)
	assert.Equal(t, SourceEnv, creds.SecretKeySource)
}

func TestLoadFrom_mixedSources(t *testing.T) {
	home := t.TempDir()
	writeTestConfig(t, home, "file-access", "file-secret")

	// Only access key in env; secret falls through to file.
	env := map[string]string{"UPBIT_ACCESS_KEY": "env-access"}
	creds, err := LoadFrom(func() (string, error) { return home, nil }, func(k string) string { return env[k] })
	require.NoError(t, err)
	assert.Equal(t, "env-access", creds.AccessKey)
	assert.Equal(t, SourceEnv, creds.AccessKeySource)
	assert.Equal(t, "file-secret", creds.SecretKey)
	assert.Equal(t, SourceFile, creds.SecretKeySource)
}

func TestLoadFrom_brokenToml(t *testing.T) {
	home := t.TempDir()
	configDir := filepath.Join(home, ".upbit")
	require.NoError(t, os.MkdirAll(configDir, 0700))
	require.NoError(t, os.WriteFile(filepath.Join(configDir, "config"), []byte("not valid toml [[["), 0600))

	_, err := LoadFrom(func() (string, error) { return home, nil }, func(string) string { return "" })
	require.Error(t, err)
	assert.Contains(t, err.Error(), "failed to parse")
	assert.Contains(t, err.Error(), "upbit config set")
}

func TestLoadFrom_loosePermissionsWarning(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("permission test not applicable on Windows")
	}
	home := t.TempDir()
	writeTestConfig(t, home, "ak", "sk")
	configPath := filepath.Join(home, ".upbit", "config")
	require.NoError(t, os.Chmod(configPath, 0644))

	// Capture stderr
	origStderr := os.Stderr
	r, w, err := os.Pipe()
	require.NoError(t, err)
	os.Stderr = w

	_, loadErr := LoadFrom(func() (string, error) { return home, nil }, func(string) string { return "" })

	w.Close()
	os.Stderr = origStderr

	var buf bytes.Buffer
	buf.ReadFrom(r)
	r.Close()

	require.NoError(t, loadErr)
	assert.Contains(t, buf.String(), "warning")
	assert.Contains(t, buf.String(), "loose permissions")
}

func TestSaveRoundtrip(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	// Patch os.UserHomeDir via Save which calls Path() which calls os.UserHomeDir.
	// To make this testable without patching, we directly manipulate the config dir.
	configDir := filepath.Join(home, ".upbit")
	require.NoError(t, os.MkdirAll(configDir, 0700))

	// Use a custom path approach: write directly then verify with readFile.
	path := filepath.Join(configDir, "config")

	c := Credentials{AccessKey: "saved-access", SecretKey: "saved-secret"}

	// Open and write manually to avoid the os.UserHomeDir issue in CI.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	require.NoError(t, err)
	header := "# Upbit CLI credentials.\n# Managed by `upbit config set`. Do not edit manually unless you know what you are doing.\n\n"
	_, err = f.WriteString(header)
	require.NoError(t, err)
	cfg := configFile{}
	cfg.Default.AccessKey = c.AccessKey
	cfg.Default.SecretKey = c.SecretKey
	require.NoError(t, toml.NewEncoder(f).Encode(cfg))
	f.Close()

	require.NoError(t, os.Chmod(path, 0600))

	// Verify via readFile
	loaded, err := readFile(path)
	require.NoError(t, err)
	assert.Equal(t, "saved-access", loaded.Default.AccessKey)
	assert.Equal(t, "saved-secret", loaded.Default.SecretKey)

	// Verify permissions
	info, err := os.Stat(path)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), info.Mode().Perm())
}

func TestSave_setsPermissions(t *testing.T) {
	if testing.Short() {
		t.Skip()
	}
	home := t.TempDir()
	t.Setenv("HOME", home)

	// Save should create ~/.upbit/ and config with correct permissions.
	c := Credentials{AccessKey: "ak", SecretKey: "sk"}
	err := Save(c)
	require.NoError(t, err)

	path := filepath.Join(home, ".upbit", "config")
	info, err := os.Stat(path)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), info.Mode().Perm())

	dirInfo, err := os.Stat(filepath.Dir(path))
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0700), dirInfo.Mode().Perm())

	// Verify content can be read back.
	loaded, err := readFile(path)
	require.NoError(t, err)
	assert.Equal(t, "ak", loaded.Default.AccessKey)
	assert.Equal(t, "sk", loaded.Default.SecretKey)

	// Verify header comment is present.
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(data), "# Upbit CLI credentials."))
}

// writeTestConfig writes a minimal valid config TOML to home/.upbit/config.
func writeTestConfig(t *testing.T, home, accessKey, secretKey string) {
	t.Helper()
	configDir := filepath.Join(home, ".upbit")
	require.NoError(t, os.MkdirAll(configDir, 0700))
	content := "[default]\naccess_key = \"" + accessKey + "\"\nsecret_key = \"" + secretKey + "\"\n"
	require.NoError(t, os.WriteFile(filepath.Join(configDir, "config"), []byte(content), 0600))
}
